### ISSUE TITLE
ImportError: No module named ImageOps test_qr.py

### ISSUE THREAD

**Issue by matburnham** [bitly/pyqrencode#2]
Whether I pip install pyqrencode or python setup.py install from source I get an exception from test_qr.py

Traceback (most recent call last):
  File "test_qr.py", line 1, in <module>
    from qrencode import Encoder
  File "qrencode.pyx", line 1, in init qrencode (qrencode.c:1520)
    from ImageOps import expand
ImportError: No module named ImageOps

**Comment by jehiah** [comment]
ImageOps is from [PIL](http://www.pythonware.com/products/pil/) which you also need installed.
